from fastapi import APIRouter
from app.api.v1 import auth, documents, iso9001, admin, diagnosticos, contexto, planificacion, procesos, auditorias, huella, kpi_api, revision_api, reportes, cambio_api, equipo_api, capacitacion_api, satisfaccion_api, ia_api, proveedor_api, sst_api, mantenimiento_api, onboarding, tenant_settings, users

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(onboarding.router, prefix="/onboarding", tags=["onboarding"])
api_router.include_router(tenant_settings.router, prefix="/tenant", tags=["tenant_settings"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(iso9001.router, prefix="/iso9001", tags=["iso9001"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(diagnosticos.router, prefix="/diagnosticos", tags=["diagnosticos"])
api_router.include_router(contexto.router, prefix="/contexto", tags=["contexto"])
api_router.include_router(planificacion.router, prefix="/planificacion", tags=["planificacion"])
api_router.include_router(procesos.router, prefix="/procesos", tags=["procesos"])
api_router.include_router(auditorias.router, prefix="/auditorias", tags=["auditorias"])
api_router.include_router(huella.router, prefix="/huella", tags=["huella"])
api_router.include_router(kpi_api.router, prefix="/kpis", tags=["kpis"])
api_router.include_router(revision_api.router, prefix="/revisiones", tags=["revisiones"])
api_router.include_router(reportes.router, prefix="/reportes", tags=["reportes"])
api_router.include_router(cambio_api.router, prefix="/cambios", tags=["cambios"])
api_router.include_router(equipo_api.router, prefix="/equipos", tags=["equipos"])
api_router.include_router(capacitacion_api.router, prefix="/capacitaciones", tags=["capacitaciones"])
api_router.include_router(satisfaccion_api.router, prefix="/satisfaccion", tags=["satisfaccion"])
api_router.include_router(ia_api.router, prefix="/ia", tags=["ia"])
api_router.include_router(proveedor_api.router, prefix="/proveedores", tags=["proveedores"])
api_router.include_router(sst_api.router, prefix="/sst", tags=["sst"])
api_router.include_router(mantenimiento_api.router, prefix="/mantenimiento", tags=["mantenimiento"])
